export type Language = "en" | "ar";

export const copy = {
  en: {
    assessment: "Assessment",
    results: "Results",
    teacher: "Teacher Dashboard",
    adaptive: "Adaptive level",
    question: "Question",
    of: "of",
    choose: "Select the one best answer.",
    submit: "Submit answer",
    next: "Next question",
    finish: "Finish assessment",
    correct: "Correct",
    incorrect: "Incorrect",
    correctAnswer: "Correct answer",
    learningSignal: "Learning signal",
    fallback: "Verified fallback",
    grounded: "Textbook grounded",
    preparing: "Preparing your next question…",
    grounding: "Grounding it in your textbook…",
    complete: "Assessment complete",
    score: "Score",
    viewResults: "View results",
    newAttempt: "Start new attempt",
    finalLevel: "Final adaptive level",
    accuracy: "accuracy",
    retry: "Retry",
    sync: "Your progress is being synchronized. Another submission is safely blocked.",
  },
  ar: {
    assessment: "التقييم",
    results: "النتائج",
    teacher: "لوحة المعلم",
    adaptive: "المستوى التكيفي",
    question: "السؤال",
    of: "من",
    choose: "اختر الإجابة الصحيحة.",
    submit: "إرسال الإجابة",
    next: "السؤال التالي",
    finish: "إنهاء التقييم",
    correct: "إجابة صحيحة",
    incorrect: "إجابة غير صحيحة",
    correctAnswer: "الإجابة الصحيحة",
    learningSignal: "ملاحظة تعليمية",
    fallback: "سؤال احتياطي موثوق",
    grounded: "مستند إلى الكتاب الدراسي",
    preparing: "جارٍ إعداد السؤال التالي…",
    grounding: "جارٍ ربطه بمحتوى كتابك…",
    complete: "اكتمل التقييم",
    score: "النتيجة",
    viewResults: "عرض النتائج",
    newAttempt: "بدء محاولة جديدة",
    finalLevel: "المستوى التكيفي النهائي",
    accuracy: "دقة",
    retry: "إعادة المحاولة",
    sync: "جارٍ مزامنة تقدمك. تم إيقاف أي إرسال آخر حفاظًا على نتيجتك.",
  },
} as const;
